S1 us02 form add part
WildCodeSchool-2023-09/PHP-paris-p2-cyclaid pull request #1
Opened 2023-11-02 16:17 UTC by NicoDestephen

I create a form to add parts to the database. Inclusion of front and back security.
I also made the CSS of the form page

2023-11-02 18:29 UTC, Baptiste1828 commented on src/Controller/PartController.php
> +        echo $this->twig->render('Part\index.html.twig', ['errors' => $errors]);
Tu peux directement rediriger vers ton _form.html.twig, ton fichier index.html.twig qui est dans ton dossier Part fait juste une redirection vers ton form en mettant ton form dans le block content et et en extendant ton layout.
Tu peux faire ces deux choses directement dans le form.html.twig et comme ça plus besoin du index.html.twig qui est dans le dossier Part, ça te pemet d'avoir un fichier en moins qui ne sert pas vraiment =)

2023-11-02 18:29 UTC, Baptiste1828 commented on public/assets/css/style.css
>  body {
Ne met pas de propriété css directement sur le body car nous allons tous travailler à partir du même, met plutôt ta partie dans une section avec un id form_add et met ces propriétés sur cette section

2023-11-02 18:29 UTC, Baptiste1828 commented on public/assets/css/style.css
> +#alert {
Si j'ai bien regardé, je n'ai vu aucune balise HTML avec un id alert

2023-11-02 18:29 UTC, Baptiste1828 commented on src/View/layout.html.twig
>      <link rel="stylesheet" href="/assets/css/style.css">
Met plutôt tout ton code css (sauf les polices au début et les propriétés appliquées sur *) dans un fichier css différent que tu mettras ensuite dans le bloc twig stylesheet dans ton form.html.twig =)

2023-11-02 19:28 UTC, Baptiste1828 approved these changes
C'est bon pour moi !

2023-11-03 11:00 UTC, mickaellambert requested changes

2023-11-03 11:00 UTC, mickaellambert commented on src/View/layout.html.twig
> +    <link href="https://www.dafontfree.net/embed/cG9zdC1uby1iaWxscy1jb2xvbWJvLWJvbGQmZGF0YS80NDEvcC8xNzk4MjAvUG9zdE5vQmlsbHNDb2xvbWJvLUJvbGQudHRm" rel="stylesheet" type="text/css"/>
J'ai vu que tu avais ajouté un dossier font avec des fichiers en local et la tu l'importes via une URL. Tu préfères quelle solution ?

2023-11-03 11:00 UTC, mickaellambert commented on public/assets/css/add_form.css
> +#navbar {
Propriété CSS de navbar dans le "add_form" c'est pas hyper logique

2023-11-03 11:00 UTC, mickaellambert commented on public/assets/css/add_form.css
> +.row {
pareil, ici tu touches à une classe CSS bootstrap de base, je suis pas sur que ce soit le bon endroit

2023-11-03 11:00 UTC, mickaellambert commented on public/assets/css/add_form.css
> +    /* position: absolute; */
pas de commentaire inutile dans le code

2023-11-03 11:00 UTC, mickaellambert commented on public/assets/css/add_form.css
> +#footer {
Ici, t'as le CSS du footer dans le add_form

2023-11-03 11:00 UTC, mickaellambert commented on public/assets/css/add_form.css
De manière globale je trouve que tes sélecteurs CSS sont très permissifs, à tout moment tu rajoutes une classe title pour quelque chose d'autre, ça fout la merde dans ton CSS 

Ce serait bien que tu viennes + en précision sur les sélecteurs (genre #form-add .input-group #mon-input

2023-11-03 11:00 UTC, mickaellambert commented on src/Controller/PartController.php
> +    public function addPart()
Pas besoin du "part" dans "addPart"

2023-11-03 11:00 UTC, mickaellambert commented on src/Controller/PartController.php
> +            $authorizedExtensions = ['jpg','png', 'jpeg', 'webp'];
En faire une constante dans le controlleur

2023-11-03 11:00 UTC, mickaellambert commented on src/Controller/PartController.php
> +            $maxFileSize = 10000000;
En faire une constante dans le controlleur

2023-11-03 11:00 UTC, mickaellambert commented on src/Controller/PartController.php
> +            if (strlen($data['description']) > 2000) {
En faire une constante dans le controlleur

2023-11-03 11:00 UTC, mickaellambert commented on src/Controller/PartController.php
> +                $data = $_POST;
Attention à ça, tu perds tout ton nettoyage de données si tu dis que à la fin, $data = $_POST

2023-11-03 11:00 UTC, mickaellambert commented on src/Controller/PartController.php
> +                    return $this->addPart();
Ici, utilises plutôt une redirection que l'appel à la fonction d'un controler

2023-11-03 11:00 UTC, mickaellambert commented on src/View/Part/_form.html.twig
> +                            <option value="Accessories">Accessories</option>
Il pourrait être malin de lister les catégories dans une constante que vous mettriez dans PartManager et que vous pourriez utiliser dans vos requêtes, dans votre affichage et dans vos controles

2023-11-03 11:00 UTC, mickaellambert commented on src/View/Part/_form.html.twig
> +                            <option value="New">New</option>
Il pourrait être malin de lister les états dans une constante que vous mettriez dans PartManager et que vous pourriez utiliser dans vos requêtes, dans votre affichage et dans vos controles

2023-11-03 11:00 UTC, mickaellambert commented on src/View/Part/_form.html.twig
> +                            <option value="">BRAND</option>
Il pourrait être malin de lister les marques dans une constante que vous mettriez dans PartManager et que vous pourriez utiliser dans vos requêtes, dans votre affichage et dans vos controles

2023-11-03 11:00 UTC, mickaellambert commented on src/View/Part/_form.html.twig
> +                            <option value="Auvergne">Auvergne</option>
Il pourrait être malin de lister les régions d'habitation dans une constante que vous mettriez dans PartManager et que vous pourriez utiliser dans vos requêtes, dans votre affichage et dans vos controles

2023-11-05 21:37 UTC, mickaellambert requested changes
Globalement bravo c'est du très bon travail ! 

Il manque juste quelques petits détails afin que ce soit parfait, notamment sur l'utilisation de tes constantes contenant toutes tes catégories etc (on voit ça ensemble, ce sera plus facile)

Il faut aussi résoudre les conflits que tu as. En effet j'ai mergé deux PR de Baptiste entre temps donc je pense qu'il a touché à des fichiers auxquels tu touche (petit pull de dev et merge dans ta branche)

2023-11-05 21:37 UTC, mickaellambert commented on public/assets/css/add_form.css
> +#textFile_select {
Attention, ici tu utilises et du camelCase et du snake_case !

2023-11-05 21:37 UTC, mickaellambert commented on src/Controller/PartController.php
> +    public const EXTENTIONS = ['jpg','png', 'jpeg', 'webp'];
EXTENSIONS*

2023-11-05 21:37 UTC, mickaellambert commented on src/Controller/PartController.php
> +    public function add()
petit saut de ligne juste au dessus ici je suis preneur merciiii

2023-11-07 13:06 UTC, mickaellambert requested changes

2023-11-07 13:06 UTC, mickaellambert commented on src/Controller/PartController.php
> +            // foreach($data as $field) {
Pas de commentaire inutile stp !

2023-11-07 13:06 UTC, mickaellambert commented on src/Controller/PartController.php
> +                    header('Location:/Home/index.html.twig');
T'a pas envie de rediriger vers la page de la pièce que tu viens d'ajouter plutôt que vers la home ?

2023-11-07 13:06 UTC, mickaellambert commented on src/Controller/PartController.php
> +        echo $this->twig->render('Part\_form.html.twig', ['errors' => $errors]);
La fonction d'un controller est censé retourner un string, la t'affiches le rendu de la fonction `render`. 
Il faudrait que tu retournes le rendu de la fonction `render` plutôt

2023-11-07 13:06 UTC, mickaellambert commented on src/Model/PartManager.php
> +        $query = "SELECT id FROM category WHERE label LIKE :category;";
haha malin mais non justement on va pas faire comme ça, on va ajouter l'id de la catégorie en tant que value de l'option à sélectionner dans ton front plutôt

2023-11-08 11:44 UTC, mickaellambert requested changes

2023-11-08 11:44 UTC, mickaellambert commented on src/Controller/PartController.php
> +            $uploadDir = 'uploads/';
Peut être en faire une constante plus globale dans le fichier de conf ?

2023-11-08 11:44 UTC, mickaellambert commented on src/Controller/PartController.php
> +            if ($this->checkIsEmpty($data)) {
saut de ligne avant le if stp

2023-11-08 11:44 UTC, mickaellambert commented on src/Controller/PartController.php
> +            }
saut de ligne avant le if stp

2023-11-08 11:44 UTC, mickaellambert commented on src/Controller/PartController.php
> +                $filesCount = count($_FILES['file']['name']);
filesCount n'est utilisé qu'une seule fois, pas besoin d'en faire une variable

2023-11-08 11:44 UTC, mickaellambert commented on src/Controller/PartController.php
> +                    $extension = pathinfo($_FILES['file']['name'][$i], PATHINFO_EXTENSION);
extension n'est utilisé qu'une seule fois, pas besoin d'en faire une variable

2023-11-08 11:44 UTC, mickaellambert commented on src/Controller/PartController.php
> +                    $uploadFile = $uploadDir . $pictures[$i];
uploadFile n'est utilisé qu'une seule fois, pas besoin d'en faire une variable

2023-11-08 11:44 UTC, mickaellambert commented on src/Controller/PartController.php
> +                if ($this->partManager->insert($data, $pictures)) {
saut de ligne avant le if stp

2023-11-08 11:44 UTC, mickaellambert commented on src/Controller/PartController.php
> +        return $this->twig->render('Part\_form.html.twig', [
saut de ligne avant le return stp

2023-11-08 11:44 UTC, mickaellambert commented on src/Controller/PartController.php
> +                    header('Location:/Home/index.html.twig');
On a envie d'être redirigé vers l'index lorsqu'on ajoute une pièce ? Pas vers la page de la pièce qu'on vient d'ajouter ?

2023-11-08 11:44 UTC, mickaellambert commented on src/Controller/PartController.php
> +        if (empty($this->errors)) {
vous pouvez juste faire un `return empty($this->errors);` a la place de tout ce if

2023-11-08 11:44 UTC, mickaellambert commented on src/Model/PartManager.php
> +    public function insert(array $data, array $pictures): int|false
saut de ligne avant la fonction stp

2023-11-08 11:44 UTC, mickaellambert commented on src/Model/PartManager.php
> +        if ($postId) {
saut de ligne avant le if stp

2023-11-08 11:44 UTC, mickaellambert commented on src/Model/PicturePartManager.php
> +    public function insertPicture(string $picture, int $id)
Pas besoin de préciser Picture dans le naming ici, on le comprend car on est dans un PicturePartManager

Donc fonction à renommer en "insert"

2023-11-08 13:12 UTC, Baptiste1828 commented on src/Controller/PartController.php
> +            $uploadDir = 'uploads/';
Done !

2023-11-08 13:15 UTC, Baptiste1828 commented on src/Controller/PartController.php
> +                $filesCount = count($_FILES['file']['name']);
Alors au début je voulais le mettre directement dans la boucle, mais le barbu refuse de mettre un count() dans une boucle, c'est pour ça que j'ai défini cette variable

2023-11-08 13:20 UTC, Baptiste1828 commented on src/Controller/PartController.php
> +                    header('Location:/Home/index.html.twig');
On  a pas encore la page de la pièce implémenté dans le code, du coup on redirigera quand on aura cette partie. Ou si tu préfère on peut rediriger vers la page mais ça fera une erreur 404 pour le moment

2023-11-08 15:08 UTC, mickaellambert approved these changes

2023-11-08 15:08 UTC, merged