S4 us06 home page
WildCodeSchool-2023-09/PHP-paris-p2-cyclaid pull request #12
Opened 2023-11-17 15:16 UTC by NicoDestephen

Create home page and change nav bar for form page

2023-11-20 10:20 UTC, mickaellambert requested changes

2023-11-20 10:20 UTC, mickaellambert commented on src/routes.php
> +    'index/index' => ['PostController', 'index', ['postsList']],
index/index ?

2023-11-20 10:20 UTC, mickaellambert commented on src/Controller/PostController.php
> +                    header('Location: /index/index');
Pas sur du naming de cette route !

2023-11-20 10:20 UTC, mickaellambert commented on src/Controller/PostController.php
> +        return $this->twig->render('Index/index.html.twig', ['postsList' => $postsList]);
idem

2023-11-20 10:20 UTC, mickaellambert commented on src/View/Post/_form.html.twig
Essaie de bien compartimenter tes modifications, je ne suis pas censé avoir des modifs d'une vue qui ne concerne pas la home dans la PR de la home

2023-11-20 10:34 UTC, Baptiste1828 commented on src/View/Index/index.html.twig
> +                            <img class = "cardIconLocation" src = "/../assets/images/icon_location.png">
Il serait peut être malin d'enlever les deux points ?

2023-11-20 10:34 UTC, Baptiste1828 commented on src/View/Index/index.html.twig
> +                            <img class = "cardIconCalendar" src = "/../assets/images/icon_calendar.png">
Il serait peut être malin d'enlever les deux points ?

2023-11-20 10:34 UTC, Baptiste1828 commented on src/View/navbar.html.twig
> +                <a href="../"><img class = "navButtons" src="/assets/images/icon_home.png"></a>
Il serait peut être malin d'enlever les deux points ?

2023-11-20 10:34 UTC, Baptiste1828 commented on src/View/navbar.html.twig
> +                <a href="../index/index"><img class = "navButtons" src="/assets/images/icon_search.png"></a>
Il serait peut être malin d'enlever les deux points ?

2023-11-20 13:14 UTC, NicoDestephen commented on src/View/Index/index.html.twig
> +                            <img class = "cardIconLocation" src = "/../assets/images/icon_location.png">
done

2023-11-20 13:14 UTC, NicoDestephen commented on src/View/Index/index.html.twig
> +                            <img class = "cardIconCalendar" src = "/../assets/images/icon_calendar.png">
done

2023-11-20 13:14 UTC, NicoDestephen commented on src/View/navbar.html.twig
> +                <a href="../"><img class = "navButtons" src="/assets/images/icon_home.png"></a>
done

2023-11-20 13:14 UTC, NicoDestephen commented on src/View/navbar.html.twig
> +                <a href="../index/index"><img class = "navButtons" src="/assets/images/icon_search.png"></a>
done

2023-11-20 13:15 UTC, NicoDestephen commented on src/View/Post/_form.html.twig
oui c'est vrai tu à raison désolé je vais faire plus attention la prochaine fois

2023-11-20 13:34 UTC, NicoDestephen commented on src/routes.php
> +    'index/index' => ['PostController', 'index', ['postsList']],
c'est bon j'ai fait la modif pour post/index

2023-11-20 13:34 UTC, NicoDestephen commented on src/Controller/PostController.php
> +                    header('Location: /index/index');
c'est bon j'ai fait la modif pour post/index

2023-11-20 13:34 UTC, NicoDestephen commented on src/Controller/PostController.php
> +        return $this->twig->render('Index/index.html.twig', ['postsList' => $postsList]);
c'est bon j'ai fait la modif pour post/index

2023-11-20 16:28 UTC, ArnoldMsl approved these changes
Non.

2023-11-20 20:07 UTC, Baptiste1828 approved these changes

2023-11-21 08:20 UTC, mickaellambert approved these changes

2023-11-21 08:20 UTC, merged