S2 us02 navbar
WildCodeSchool-2023-09/PHP-paris-p2-cyclaid pull request #5
Opened 2023-11-07 10:47 UTC by ArnoldMsl

Added Common navbar as a component in the twig Layout.

2023-11-07 13:32 UTC, mickaellambert requested changes

2023-11-07 13:32 UTC, mickaellambert commented on public/assets/css/navbar.css
> +
espace en trop ici

2023-11-07 13:32 UTC, mickaellambert commented on public/assets/css/navbar.css
> +  .navbuttons{
T'as oublié le camelCase sur buttons

2023-11-07 13:32 UTC, mickaellambert commented on public/assets/css/navbar.css
> +  /* part/view Header */
pas de commentaire inutile stppp merci

2023-11-07 13:32 UTC, mickaellambert commented on public/assets/css/navbar.css
> +  text-align: right;
attention à l'indentation !

2023-11-07 13:32 UTC, mickaellambert commented on src/Controller/PostController.php
Pourquoi ajouter des fonctions d'affichage d'un post et de listing de tous les posts sur une US qui concerne une navbar ?

2023-11-07 13:32 UTC, mickaellambert commented on src/Model/PostManager.php
Même question que pour le controlleur

2023-11-07 13:32 UTC, mickaellambert commented on src/View/Post/show.html.twig
> +{# Carousel : à modifier et débugger #}
Pas de commentaire inutile. 
Et pas de code envoyé qui n'est pas débugger et finalisé

2023-11-07 13:32 UTC, mickaellambert commented on src/View/Post/show.html.twig
> +$('#myCarousel').carousel({
Est ce que tu comprends une seconde ce que tu fais à partir d'ici ? haha

2023-11-07 13:32 UTC, mickaellambert commented on src/View/layout.html.twig
> +
trop d'espace ici

2023-11-07 13:32 UTC, mickaellambert commented on src/View/layout.html.twig
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></s
vous avez pas intégré bootstrap localement ?

2023-11-07 13:32 UTC, mickaellambert commented on src/View/layout.html.twig
> +    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
pourquoi pas installer jquery dans votre projet mais je trouve ça un peu tôt pour une US de navbar

2023-11-07 13:32 UTC, mickaellambert commented on src/routes.php
> +    'post/show' => ['PostController', 'show', ['id']],
Pourquoi ajouter une route d'affichage d'un post sur une US qui concerne juste la navbar ?

2023-11-07 14:23 UTC, ArnoldMsl commented on public/assets/css/navbar.css
> +
done

2023-11-07 14:23 UTC, ArnoldMsl commented on public/assets/css/navbar.css
> +  .navbuttons{
done

2023-11-07 14:23 UTC, ArnoldMsl commented on public/assets/css/navbar.css
> +  /* part/view Header */
done

2023-11-07 14:23 UTC, ArnoldMsl commented on public/assets/css/navbar.css
> +  text-align: right;
done

2023-11-07 14:25 UTC, ArnoldMsl commented on src/Controller/PostController.php
Ma branche précédente S1_US03 n'a pas encore été Pull. Je peux tout supprimer si c'est vraiment nécessaire.

2023-11-07 14:26 UTC, ArnoldMsl commented on src/Model/PostManager.php
même réponse

2023-11-07 14:27 UTC, ArnoldMsl commented on src/View/Post/show.html.twig
> +{# Carousel : à modifier et débugger #}
Done

2023-11-07 14:27 UTC, ArnoldMsl commented on src/View/Post/show.html.twig
> +$('#myCarousel').carousel({
C'est du Bootstrap (qui en fonctionne pas d'ailleurs) c'était un test que j'ai oublié de supprimer.

2023-11-07 14:28 UTC, ArnoldMsl commented on src/View/layout.html.twig
> +
J'en ai enlevé quelques-uns, c'est mieux ?

2023-11-07 14:29 UTC, ArnoldMsl commented on src/View/layout.html.twig
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></s
On a tenté, sans succès

2023-11-07 14:29 UTC, ArnoldMsl commented on src/View/layout.html.twig
> +    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
c'était pour le carousel Bootstrap qui ne fonctionnait pas, oubli de suppression.

2023-11-07 14:30 UTC, ArnoldMsl commented on src/routes.php
> +    'post/show' => ['PostController', 'show', ['id']],
même réponse que pour les post controllers et managers

2023-11-07 15:00 UTC, mickaellambert requested changes

2023-11-07 15:00 UTC, mickaellambert commented on src/Controller/PostController.php
> +    public function showAll()
on pourrait appeler cette fonction "list" ou "index"

2023-11-07 15:00 UTC, mickaellambert commented on src/Controller/PostController.php
> +class PostController extends AbstractController
Ajouter le postManager en tant que propriété de PostController

2023-11-07 15:00 UTC, mickaellambert commented on src/Controller/PostController.php
> +        $post = $postManager->showPost($id);
Une fonction qui te permet de sélectionner un élement grâce à un id existe déjà dans ton manager (indice : regarde la classe mère)

2023-11-07 15:00 UTC, mickaellambert commented on src/Model/PostManager.php
> +    public function showPost(int $id)
Comme dit précdemment, cette fonction existe déjà (regarde la classe mère)

2023-11-07 15:00 UTC, mickaellambert commented on src/Model/PostManager.php
> +    public function showAllPosts(): array
Cette fonction existe déjà aussi dans ton manager

2023-11-07 15:00 UTC, mickaellambert commented on src/View/Home/index.html.twig
> +            <li><a href="/post/show?id={{ post.id }}"> - {{ post.id }} {{ post.title }}</a></li>
Si tu fais des "li" il faut faire un "ul"

2023-11-07 15:00 UTC, mickaellambert commented on src/View/Post/show.html.twig
> +{% block content %}
Ne pas envoyer de HTML qui n'est pas fini

2023-11-08 15:09 UTC, mickaellambert approved these changes

2023-11-08 15:25 UTC, mickaellambert approved these changes

2023-11-08 15:25 UTC, merged