S02 bug fix after merge
WildCodeSchool-2023-09/PHP-paris-p2-cyclaid pull request #8
Opened 2023-11-09 15:40 UTC by NicoDestephen

fix bug : 
- css
- routes
- PartManager / PartController / PicturePartManager
- 
We have to debug js script for preview

2023-11-09 15:54 UTC, mickaellambert requested changes

2023-11-09 15:54 UTC, mickaellambert commented on public/assets/css/style.css
> +  background-color: #E6E6E6;
Faut peut être utiliser vos variables CSS du coup non ?

2023-11-09 15:54 UTC, mickaellambert commented on public/assets/css/style.css
>      background-color: #152905;
Faut peut être utiliser vos variables CSS du coup non ?

2023-11-09 15:54 UTC, mickaellambert commented on src/View/layout.html.twig
> +    <!--<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
pas de commentaire inutile stp !

2023-11-09 15:54 UTC, mickaellambert commented on src/View/layout.html.twig
> +  -->  {% block javascript %}{% endblock %}
qu'est ce que c'est "-->" ?

2023-11-09 21:26 UTC, Baptiste1828 approved these changes
Ca me parait bon, les choses à corriger ont été faite.

2023-11-10 13:08 UTC, mickaellambert requested changes

2023-11-10 13:08 UTC, mickaellambert commented on public/assets/js/form.js
> +  function changeInputFil(oEvent){
il manque le "e"

2023-11-10 13:08 UTC, mickaellambert commented on src/Model/PartManager.php
> +
ligne en trop ici

2023-11-10 13:08 UTC, mickaellambert commented on src/View/Part/_form.html.twig
> +            <form name="myForm"action="" method="post" enctype="multipart/form-data">
myForm comme name c'est pas fou

2023-11-10 13:08 UTC, mickaellambert commented on src/View/layout.html.twig
> +<link rel="stylesheet" href="/assets/css/navbar.css">
indentation ici

2023-11-10 15:35 UTC, mickaellambert requested changes

2023-11-10 15:35 UTC, mickaellambert commented on src/Model/PartManager.php
> +use App\Model\PicturePartManager;
?

2023-11-13 14:04 UTC, mickaellambert approved these changes

2023-11-13 14:04 UTC, mickaellambert commented on public/uploads/654e540956be9.webp
git ignore

2023-11-13 14:04 UTC, merged