S2 us01 index view
WildCodeSchool-2023-09/PHP-paris-p2-cyclaid pull request #9
Opened 2023-11-13 11:21 UTC by ArnoldMsl

Added the dynamic index showing all the posts in the database and a few detailed examples for testing purposes.

Each card is a button to get to the detailed view of the post.

2023-11-14 11:11 UTC, Baptiste1828 requested changes

2023-11-14 11:11 UTC, Baptiste1828 commented on src/routes.php
> +    'part/add' => ['PostController', 'add'],
Ta classe qui contient la méthode add s'appelle PostController, le naming de la route n'est pas cohérent =)

2023-11-14 11:11 UTC, Baptiste1828 commented on public/assets/css/style.css
> -}
Le footer est sur toutes les pages, autant le laisser dans le fichier css principal, sinon tu vas devoir le recopier dans chacun des fichiers css de chaque page

2023-11-14 11:11 UTC, Baptiste1828 commented on public/assets/css/searchbar.css
> +    background-color: var(--background-color);
Ta couleur de background est déjà défini dans style.css sur l'élément html, donc cela répète du code =)

2023-11-14 11:26 UTC, ArnoldMsl commented on src/routes.php
> +    'part/add' => ['PostController', 'add'],
Done. Vous pouvez prévenir quand vous modifiez des éléments structurants comme ça ? ça évitera d'avoir à repasser sur tous le code après coup

2023-11-14 11:27 UTC, ArnoldMsl commented on public/assets/css/style.css
> -}
done

2023-11-14 11:28 UTC, ArnoldMsl commented on public/assets/css/searchbar.css
> +    background-color: var(--background-color);
done

2023-11-14 14:26 UTC, mickaellambert requested changes

2023-11-14 14:26 UTC, mickaellambert commented on src/View/carIdmageSelect.html.twig
tu t'es pas reluuuuuu

2023-11-14 14:26 UTC, mickaellambert commented on database.sql
> +INSERT INTO post (title, reference, creation_date, description, wear_status, user_id, brand_id, category_id) VALUES ('Test1', 'Ref1', NOW(), 'Il roule, et il roule vite !!! Il a des pédales, appelés
On ne pousse pas des valeurs de test déso, soit des vrais posts pour l'installation du projet, soit rien :)

2023-11-14 14:26 UTC, mickaellambert commented on public/assets/css/index.css
Globamenent je compends rien à vos fichiers CSS vous avez un style.css un index.css et puis des css par fonctionnalité, c'est un peu le bordel honnêtement

2023-11-14 14:26 UTC, mickaellambert commented on public/assets/images/calendar_icon.png
Il me faudrait de la cohérence dans le naming des images stp, 

il y en a qui ont un "e" à "icone" d'autres qui commence par "icon", d'autres qui terminent par "icon" 

bref c'est le bordel

2023-11-14 14:26 UTC, mickaellambert commented on public/uploads/test1.jfif
Le dossier d'uploads va dans le gitignore

2023-11-14 14:26 UTC, mickaellambert commented on src/Model/AbstractManager.php
> +        $query = 'SELECT * FROM ' . static::TABLE .
Alors, surtout pas, t'es en train de toucher à la fonction selectAll présente pour tous tes managers, et la tu la rends inutilisable hors d'un contexte de "post_picture"

2023-11-14 18:01 UTC, mickaellambert requested changes

2023-11-14 18:01 UTC, mickaellambert commented on src/Model/PostManager.php
> +    public function index(string $orderBy = '', string $direction = 'ASC'): array
la fonction devrait s'appeler selectAll() afin d'être une surcharge de celle du controller mere

2023-11-14 18:01 UTC, mickaellambert commented on public/uploads/test1.jfif
Du coup on garde ?

2023-11-15 06:07 UTC, ArnoldMsl commented on src/Model/PostManager.php
> +    public function index(string $orderBy = '', string $direction = 'ASC'): array
hmmmmm, faudra que tu m'expliques ce que tu entends

2023-11-15 06:09 UTC, ArnoldMsl commented on public/uploads/test1.jfif
oui si ça te convient : j'ai modifié les autres entrées par des "vraies" données mais à part mettre un nom de photo issu d'un appareil photo type "DCIM0125845289346.jpeg" je ne vois pas trop l'intérêt de les renommer

2023-11-15 22:13 UTC, Baptiste1828 approved these changes

2023-11-15 23:37 UTC, mickaellambert approved these changes

2023-11-15 23:37 UTC, merged